const errorCodes = {
  // User
  INVALID_INPUT: "USR001",
  INVALID_CREDENTIALS: "USR002",
  USER_ALREADY_SIGNUP: "USR003",

  // Auth

  NOT_AUTHENTICATE: "AUTH001",
  NOT_TOKEN: "AUTH002",
  NOT_VALID_TOKEN: "AUTH003",
  NOT_VALID_REFRESH_TOKEN: "AUTH004",
};

export default errorCodes;
