const resultCodes = {
  // CREATE
  CREATE_SUCCESS: "CRT001",

  // UPDATE
  UPDATE_SUCCESS: "UPT001",

  // DELETE
  DELETE_SUCCES: "DEL001",

  // READ
  SELECTED_DATA: "SLD001",

  // Email
  EMAIL_SENDED_SUCCESS: "EML001",

  // SEAL
  SEAL_UPDATED_SUCCESS: "SEL001",

  // AUTH
  PWD_RESET_SUCCESS: "SAUTH001",
  SIGN_UP_SUCCESS: "SAUTH002",
  LOGOUT_SUCCESS: "SAUTH003",
};

export default resultCodes;
